header:
    title: Digital Therapeutics for Dementia
    text: <p>Cogthera<small><small><small><sup>®</sup></small></small></small></p>
    # button: Tell Me More
    # buttonlink: "#services"

services:
    title: AI based Smart Care Online Platform
    text: 
    section: services
    list:
      - title: "Screening"
        desc: ""
        icon: fas fa-binoculars 
      - title: "Monitoring"
        desc: ""
        icon: fas fa-satellite   
      - title: "Prevention"
        desc: ""
        icon: fas fa-shield-alt #find more at https://fontawesome.com/icons
      - title: "Treatment"
        desc: ""
        icon: fas fa-medal 

  
team:
    title: "TEAM"
    text: Passionate members and advisory groups from various fields are with us to improve the overall maturity of the service.
    subtext: 
    section: team
    people:
      - name: "Jun-Young Lee"
        role: "Co-Founder & CEO<br>Clinical field expert"
        image: assets/img/team/benji2.jpg
        # social:
        #  - url: https://twitter.com
          #   icon: fab fa-twitter
          # - url: https://facebook.com
          #   icon: fab fa-facebook-f
          # - url: https://linkedin.com
          #   icon: fab fa-linkedin-in
      - name: "Yoo-Hun Noh"
        role: "Co-Founder & CEO<br>Base field expert"
        image: assets/img/team/ardor2.jpg
        # social:
        #   - url: https://twitter.com
        #     icon: fab fa-twitter
        #   - url: https://facebook.com
        #     icon: fab fa-facebook-f
        #   - url: https://linkedin.com
        #     icon: fab fa-linkedin-in
      - name: "Jung Hae Youn"
        role: "Co-Founder & COO<br>Psychology field expert"
        image: assets/img/team/mint2.jpg
        # social:
        #   - url: https://twitter.com
        #     icon: fab fa-twitter
        #   - url: https://facebook.com
        #     icon: fab fa-facebook-f
        #   - url: https://linkedin.com
        #     icon: fab fa-linkedin-in              

clients:
    section: clients
    max-height: 100px
    horizontal-scrolling: "" #"yes/no"
    list:
      - title: "Seoul National University"
        url: https://en.snu.ac.kr
        logo: assets/img/clients/snu-100.jpg
      - title: "Seoul National University Hospital"
        url: http://www.snuh.org/global/en/main.do
        logo: assets/img/clients/snuh-100.jpg
      - title: "Eisai"
        url: http://www.eisaikorea.com
        logo: assets/img/clients/eisai-100.jpg
      - title: "SK telecom"
        url: https://www.sktelecom.com/index_en.html
        logo: assets/img/clients/skt-100.jpg
  
contact:
    title: "Contact Us"
    text: "contact@emocog.com"
    section: contact
    
footer:
    legal: "Privacy Policy"
    # social:
    #  - url: https://twitter.com
    #    icon: "fab fa-twitter"  
    #  - url: https://facebook.com
    #    icon: "fab fa-facebook-f"
    #  - url: https://linkedin.com
    #    icon: "fab fa-linkedin-in"
    #  - url: https://github.com/raviriley/agency-jekyll-theme
    #    icon: "fab fa-github"
    #  - url: https://instagram.com
    #    icon: "fab fa-instagram"

# portfolio:
#     title: "Portfolio"
#     text: "Lorem ipsum dolor sit amet consectetur."
#     section: portfolio
#     closebutton: "Close Project"
    

# timeline:
#     title: "About" 
#     text: "Lorem ipsum timeline"
#     section: timeline
#     # left is the default
#     #start_align: "left"
#     events:
#       - title: "Our Humble Beginnings"
#         year: "2009-2011"
#         desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
#         image: assets/img/timeline/1.jpg
#         alt: 
#       - title: "An Agency is Born"
#         year: "March 2011"
#         desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
#         image: assets/img/timeline/2.jpg
#         alt: 
#       - title: "Jekyll Theme is created"
#         year: "2019"
#         desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
#         image: assets/img/timeline/3.jpg
#         alt: image alt text
#       - title: "Title"
#         year: "2009-2011"
#         desc: "Your description here, **Markdown** is fully supported."
#         image: assets/img/timeline/4.jpg
#         alt: 
#         # you can enforce the aligment
#         align: right
#     end: "Be Part <br> of Our <br> Story!"

# about:
#     title: "About Us"
#     text: "our story"
#     section: about

# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
